name: Firebase Deploy

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g firebase-tools
      - run: npm install
      - run: npm run build
      - name: Firebase Deploy
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
